const fs = require("fs");
const Fold = require("./Folder");
// const modules = require("/node_modules");
// console.log(require.main);
console.log(__dirname);
console.log(__filename);
// console.log(process.NODE_PATH);
// console.log(exports);
// console.log(require.cache.fs);
// console.log(require.resolve.paths("./bufferByExample/buffer.js", {}));
// console.log(module.id);
// console.log(module.filename);
// console.log(module.isPreloading);
// console.log(module.loaded);
